name: Gradle Check

on:
  schedule:
    - cron: '0 */8 * * *'
  push:
    branches:
      - main
  pull_request_target:
    types: [ opened, synchronize ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - id: setup
        uses: sava-software/sava-build@main
        with:
          default-java-version: ${{ vars.JAVA_VERSION }}
          jdk-src: ${{ vars.JDK_SRC }}
          gradle-java-version: ${{ vars.GRADLE_JAVA_VERSION }}

      - name: Checkout IDL Source Generator
        uses: actions/checkout@v4
        with:
          repository: sava-software/idl-src-gen
          token: ${{ secrets.READ_SAVA_SRC_GEN }}
          path: idl-src-gen

      - name: Generate Source & Check
        run: |
          ./idl-src-gen/genSrc.sh --config="../main_net_programs.json" --rpc="${{ secrets.RPC_URL }}"
          ./gradlew --stacktrace -PjavaVersion=${{ steps.setup.outputs.java-version }} check
        env:
          ORG_GRADLE_PROJECT_savaGithubPackagesUsername: ${{ env.GITHUB_ACTOR }}
          ORG_GRADLE_PROJECT_savaGithubPackagesPassword: ${{ secrets.GITHUB_TOKEN }}
