name: Publish Release

on:
  create:
    tags:
      - '*-\d+\.\d+\.\d+'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - id: setup
        uses: sava-software/sava-build@main
        with:
          default-java-version: ${{ vars.JAVA_VERSION }}
          jdk-src: ${{ vars.JDK_SRC }}
          gradle-java-version: ${{ vars.GRADLE_JAVA_VERSION }}

      - name: Parse tag for module and version
        id: parse_tag
        shell: bash
        run: |
          TAG="${GITHUB_REF_NAME}"
          MODULE="${TAG%%-*}"
          VERSION="${TAG#*-}"
          echo "module=$MODULE" >> "$GITHUB_OUTPUT"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Checkout IDL Source Generator
        uses: actions/checkout@v4
        with:
          repository: sava-software/idl-src-gen
          token: ${{ secrets.READ_SAVA_SRC_GEN }}
          path: idl-src-gen

      - name: Generate Source & Check
        run: |
          ./idl-src-gen/genSrc.sh --config="../main_net_programs.json" --rpc="${{ secrets.RPC_URL }}"
          ./gradlew --stacktrace -PjavaVersion=${{ steps.setup.outputs.java-version }} -Pversion=${{ steps.parse_tag.outputs.version }} check
        env:
          ORG_GRADLE_PROJECT_savaGithubPackagesUsername: ${{ env.GITHUB_ACTOR }}
          ORG_GRADLE_PROJECT_savaGithubPackagesPassword: ${{ secrets.GITHUB_TOKEN }}

      - name: Maven Central
        run: ./gradlew --stacktrace -Psign=true -PjavaVersion=${{ steps.setup.outputs.java-version }} -Pversion=${{ steps.parse_tag.outputs.version }} -Pnmcp.publish.project=${{ steps.parse_tag.outputs.module }} :aggregation:publishAggregationToCentralPortal
        env:
          GPG_PUBLISH_SECRET: ${{ secrets.GPG_PUBLISH_SECRET }}
          GPG_PUBLISH_PHRASE: ${{ secrets.GPG_PUBLISH_PHRASE }}
          ORG_GRADLE_PROJECT_savaGithubPackagesUsername: ${{ env.GITHUB_ACTOR }}
          ORG_GRADLE_PROJECT_savaGithubPackagesPassword: ${{ secrets.GITHUB_TOKEN }}

      - name: Github Packages
        run: ./gradlew --stacktrace -Psign=true -PjavaVersion=${{ steps.setup.outputs.java-version }} -Pversion=${{ steps.parse_tag.outputs.version }} :idl-clients-${{ steps.parse_tag.outputs.module }}:publishMavenJavaPublicationToSavaGithubPackagesRepository
        env:
          GPG_PUBLISH_SECRET: ${{ secrets.GPG_PUBLISH_SECRET }}
          GPG_PUBLISH_PHRASE: ${{ secrets.GPG_PUBLISH_PHRASE }}
          ORG_GRADLE_PROJECT_savaGithubPackagesUsername: ${{ env.GITHUB_ACTOR }}
          ORG_GRADLE_PROJECT_savaGithubPackagesPassword: ${{ secrets.GITHUB_TOKEN }}
